messages:
  enable-placeholderapi: false
database:
  # dostepne typy baz danych: mysql yaml
  type: yaml
  mysql-settings:
    driver: "com.mysql.cj.jdbc.Driver"
    address: "localhost"
    port: 3306
    database: "minecraft"
    username: "admin"
    password: ""
  yaml-settings:
    file: "{plugin-folder}/database/database.yml"